name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout posts
      uses: actions/checkout@v2
      with:
        path: posts
    - name: Checkout config
      uses: actions/checkout@v2
      with:
        repository: mutongx/mutongx.github.io-config
        submodules: 'true'
        path: config
    - name: Checkout public
      uses: actions/checkout@v2
      with:
        repository: mutongx/mutongx.github.io
        path: public
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Constructs workspace
      run: |
        mv config workspace
        mkdir -p workspace/source
        mv public workspace/
        mv posts/* workspace/source/
    - name: Setup hexo environment
      run: |
        npm install -g hexo-cli
        npm ci
    - name: Generate pages
      run: hexo generate
